import http.client
import json

conn = http.client.HTTPSConnection("api-sandbox.inditex.com")
payload = ''
headers = {
  'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJraWQiOiJZMjZSVjltUFc3dkc0bWF4NU80bDBBd2NpSVE9IiwiYWxnIjoiUlMyNTYifQ.eyJhdF9oYXNoIjoiZzdRYlJoRXhiS2RuMWMxVnhlS2pOdyIsInN1YiI6Im9hdXRoLW1rcHNib3gtb2F1dGh5YWJtdXF1bXNsYWZjZWxpb3lzbmJ4cHJvIiwiYXVkaXRUcmFja2luZ0lkIjoiYmMxODIwODItNTlmYy00OTYyLWI5ZTQtMTIyMDg4ODYxMGUxLTEyMDQ3NzcxMCIsImN1c3RvbSI6eyJjb25zdW1lck9yZ0lkIjoibWF0ZW9ib2RlbmxsZV9nbWFpbC5jb20iLCJtYXJrZXRwbGFjZUNvZGUiOiJvcGVuLWRldmVsb3Blci1wb3J0YWwiLCJtYXJrZXRwbGFjZUFwcElkIjoiOTI1YWZkZTMtNjcxNy00NDViLThhYWUtNGQzNjBmZDQ5NWUzIn0sImlzcyI6Imh0dHBzOi8vYXV0aC5pbmRpdGV4LmNvbTo0NDMvb3BlbmFtL29hdXRoMi9pdHhpZC9pdHhpZG1wL3NhbmRib3giLCJ0b2tlbk5hbWUiOiJpZF90b2tlbiIsInVzZXJJZCI6Im9hdXRoLW1rcHNib3gtb2F1dGh5YWJtdXF1bXNsYWZjZWxpb3lzbmJ4cHJvIiwiYXVkIjoib2F1dGgtbWtwc2JveC1vYXV0aHlhYm11cXVtc2xhZmNlbGlveXNuYnhwcm8iLCJpZGVudGl0eVR5cGUiOiJzZXJ2aWNlIiwiYXpwIjoib2F1dGgtbWtwc2JveC1vYXV0aHlhYm11cXVtc2xhZmNlbGlveXNuYnhwcm8iLCJhdXRoX3RpbWUiOjE3NDAxOTY2NDksInNjb3BlIjoibWFya2V0IHRlY2hub2xvZ3kuY2F0YWxvZy5yZWFkIG9wZW5pZCIsInJlYWxtIjoiL2l0eGlkL2l0eGlkbXAvc2FuZGJveCIsInVzZXJUeXBlIjoiZXh0ZXJuYWwiLCJleHAiOjE3NDAyMDAyNTEsInRva2VuVHlwZSI6IkpXVFRva2VuIiwiaWF0IjoxNzQwMTk2NjQ5LCJhdXRoTGV2ZWwiOiIxIn0.OJuYplEMmFhQKlKcrV1LmqNr_sNbKPJUCVIwxEAuokEvra2X592oO1cvGUUrV48rGqwMTfIFiweKM9E0g7TqVnTgvhcdeWg7nxhOG9VK_n14CmNNiF1gu41DvoGsuF9QjRMMr-kNfIZPlmSDZB3tUEdHGGBtHhaSNA_NMHahPl7SCJtofNsqizi36dVoo4Xvboj0CW08A12pVH9zXCsnHr8TBHJ-wk6-AY_OTvQ023DjJGHWzTXhWle-dP-7NawbyTX44HR-2qIJvHEtVSjvdwNLRhdryWTRg0Tmnv7ji2aotGcZBvU9mkcawuHIjY3A7qqTqLGmga2rsmxWA-PsmQ',
  'Content-Type': 'application/json',
}
conn.request("GET", "/searchpmpa-sandbox/products?query=o", payload, headers)
res = conn.getresponse()
data = res.read()
print(data.decode("utf-8"))